backend:
  image: ghcr.io/vedanshun05/labboard-backend
  tag: 0760dda471aaf010996527177f6966506dff4ade
frontend:
  image: ghcr.io/vedanshun05/labboard-frontend
  tag: 0760dda471aaf010996527177f6966506dff4ade
replicaCount: 3
ingress:
  enabled: true
  host: labboard.local
hpa:
  enabled: true
