name: Artifacts Demonstration

on: push

jobs:
  produce-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build file
        run: echo "Artifact test" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-artifact
          path: test.txt
