apiVersion: v1
kind: Pod

metadata:
  name: crash-demo

spec:
  containers:
    - name: app
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "Application starting..."
          echo "Application is healthy"
          sleep 3600